id: P898A0A21
initial_creation_type: input
source_metadata:
  title: Dudjom Lingpa Series
  language: fr
  description: 'We present the following texts by and about the great tertön Dudjom
    Lingpa (bdud ''joms gling pa, 1835–1904):'
  volume:
    ab0e3a19a8a542abac1a66b9edadfd02:
      title: A Sukhāvatī Prayer and Aspiration
      parent: Aspiration Prayers
    463565b3469b413f94113490c146d129:
      title: An Aspiration
      parent: Aspiration Prayers
    43fc40b3567e45718bd9135ce136cba5:
      title: An Aspiration Prayer
      parent: Aspiration Prayers
    a7d90c56f20943b289a4ae316655c512:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Biography
    5cab68c06ae040b5a064361e032bea58:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Offering
    ec3218ba71524eb69a7ce4d49b13bb4b:
      title: The Verse for Offering Water from the Pure Vision, An Ocean of Accomplishments
      parent: Offering
    02509d06f1ea40ac91ed0d5cb91057d3:
      title: A Prayer
      parent: Prayers
    46de4cfefacd43ed8c662cbbd4d74666:
      title: A Prayer to Dudjom Lingpa
      parent: Prayers
    d1e40072965d4ea2a542f93c095a25c8:
      title: A Prayer to Padmasambhava
      parent: Prayers
    71665f3e3ad94c1993dd5e4dbabd88ae:
      title: A Prayer to Parṇaśavarī
      parent: Prayers
    fc581bcf65484a4b8b3b250f52a19806:
      title: The Outer, Inner and Secret Refuge Prayer
      parent: Refuge
    8f67c9767ed3442ba120be6cab2aeeb9:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Sādhanas
    dbe7f1df60554e8580ab76ab779f2854:
      title: Visualization and Mantra Recitation of the Great Compassionate One
      parent: Sādhanas
created_at: '2022-02-28T23:06:52.944732'
last_modified_at: '2022-02-28T23:06:52.944734'
